# This file generates the GitHub Actions matrix.
include:
  - board: seeed_xiao_ble/nrf52840
    shield: pretaporter_r
  - board: seeed_xiao_ble/nrf52840
    shield: pretaporter_l
  - board: seeed_xiao_ble/nrf52840
    shield: settings_reset
